### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by zhaojiancheng007** [Xinjie-Q/GaussianImage#5]
Thanks for your great work; it's very interesting. When I was testing the code, I often encountered issues with illegal CUDA memory access during program execution. Have you encountered this problem? What could be causing this?"
Thanks !

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Xinjie-Q** [comment]
Could you provide the running command? When I run the commands from the script, I do not have such a problem.

**Comment by zhaojiancheng007** [comment]
Hi ! here is my running script

for num_points in 1000 1500 2000
do
CUDA_VISIBLE_DEVICES=0 python train.py -d $data_path \
--data_name beauty --model_name GaussianImage_RS --num_points $num_points --iterations 30000 --save_imgs
done

This error occored kind of random, but more frequent when I tested gaussians Image using relatively high resolution data, for example 1920*960, or 1280*960.

**Comment by ChaosAdmStudent** [comment]
This issue happens when you compile gsplat during first run (JIT). When I pip install gsplat by compiling CUDA libraries on installation, everything works for me. Maybe something to try out.

**Comment by shan1921** [comment]
Has this issue been resolved? If so, how was it resolved?

**Comment by djx99** [comment]
Hi, did you solve this problem? I'm experiencing the same problem.
I found out that it is not a random problem, when the value of num_points is small, the error is reported.
I suspect that when the number of Gaussians is small, some tiles are not covered by any Gaussian. But I did not prove this.

**Comment by santolina** [comment]
I encountered the same problem when fitting a 4K image.
If the value of num_points is set sufficiently high like 0.1M, the error does not occur.

> I suspect that when the number of Gaussians is small, some tiles are not covered by any Gaussian.

I agree with this hypothesis. It seems likely that tiles without any Gaussians are causing the issue.

**Comment by jiayi1129** [comment]
For anyone looking to solve this issue, this is what I did:

1. In `gsplat/gsplat/utils.py`, pass in `tile_bounds` to `get_tile_bin_edges` function. 
2. In  `gsplat/gsplat/utils.py`, for the function `get_tile_bin_edges`, add in the parameter `tile_bounds: Tuple[int, int, int]`, and call the function like this `return _C.get_tile_bin_edges(num_intersects, isect_ids_sorted.contiguous(), tile_bounds)`
3. In `gsplat/gsplat/cuda/csrc.bindings.h`, change the function signature:
```python
torch::Tensor get_tile_bin_edges_tensor(
    int num_intersects,
    const torch::Tensor &isect_ids_sorted,
    const std::tuple<int, int, int>& tile_bounds
);
```
4. Modify the function in `bindings.cu`
```python
torch::Tensor get_tile_bin_edges_tensor(
    int num_intersects, 
    const torch::Tensor &isect_ids_sorted,
    const std::tuple<int, int, int>& tile_bounds  // Add tile_bounds parameter
) {
    CHECK_INPUT(isect_ids_sorted);
    
    // Calculate total number of tiles
    const int total_tiles = std::get<0>(tile_bounds) * std::get<1>(tile_bounds);
    
    // Initialize for ALL tiles (not just intersections)
    torch::Tensor tile_bins = torch::zeros(
        {total_tiles, 2}, isect_ids_sorted.options().dtype(torch::kInt32)
    );

    get_tile_bin_edges<<<
        (num_intersects + N_THREADS - 1) / N_THREADS,
        N_THREADS>>>(
        num_intersects,
        isect_ids_sorted.contiguous().data_ptr<int64_t>(),
        (int2 *)tile_bins.contiguous().data_ptr<int>()
    );
    return tile_bins;
}
```
5. Compile gsplat module and run your code again - voila - no more illegal memory assess error.

The reason for the error is stated by the people before this - It seems likely that tiles without any Gaussians are causing the issue.

Hope this helps someone!
